### ISSUE TITLE
chore: todo items for edk2-staging upstream

### ISSUE THREAD

**Issue by Douglas-Farley** [timberland-sig/edk2#15]
Tracking of remaining things:
- [ ] Fix a few attributions in commits (lost Peter, Swamy, Wei)
- [ ] PI Spec update for Passthrough GUID
- [ ] Nvmeofcli fixes in #13
